config/routes.rb
MediationCounters::Application.routes.draw do
  get "dashboard/index"

  root to: 'dashboard#index'
end

app/models/ggsn_counter.rb
# == Schema Information
#
# Table name: ggsn_counters
#
#  id             :integer          not null, primary key
#  filename       :string(255)
#  calltime       :datetime
#  records_in     :integer
#  records_out    :integer
#  malformed_data :integer
#  missing_data   :integer
#  zero_value     :integer
#  min_too_low    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class GgsnCounter < ActiveRecord::Base
  attr_accessible :calltime, :filename, :malformed_data, :min_too_low, 
    :missing_data, :records_in, :records_out, :zero_value
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include DashboardHelper

  def index
    #@date = params[:start_date] ? 
    #  Date.parse(params[:start_date]).beginning_of_week : 
    #  DateTime.now.beginning_of_week

    @date = get_beginning_of_week(params[:start_date])

    @current_week = @date.strftime("%U").to_i

    @daily_counters = get_counters_by_day(@date, @date.end_of_week)

    @hourly_counters = get_counters_by_hour(@date, @date.end_of_week)
  end

  def get_counters_by_day(from, to)
    #GgsnCounter.where(calltime: (from..to)).group("DATE(calltime)").sum(:records_in)
    GgsnCounter.find_by_sql(["select date(calltime) as calldate, 
                                     sum(records_in) as sum_records_in,
                                     sum(records_out) as sum_records_out,
                                     sum(malformed_data) as sum_malformed_data,
                                     sum(missing_data) as sum_missing_data,
                                     sum(zero_value) as sum_zero_value,
                                     sum(min_too_low) as sum_min_too_low
                                from ggsn_counters 
                               where calltime BETWEEN ? AND ?
                            group by date(calltime)", from, to+1])
  end

  def get_counters_by_hour(from, to)
    GgsnCounter.find_by_sql(["select date(calltime) as calldate,
                                     strftime('%H', calltime) as hour,
                                     sum(records_in) as sum_records_in,
                                     sum(records_out) as sum_records_out,
                                     sum(malformed_data) as sum_malformed_data,
                                     sum(missing_data) as sum_missing_data,
                                     sum(zero_value) as sum_zero_value,
                                     sum(min_too_low) as sum_min_too_low
                                from ggsn_counters
                               where calltime BETWEEN ? AND ?
                            group by date(calltime),
                                     strftime('%H', calltime)", from, to+1])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_date(date)
    return Date.parse(date).strftime('%a, %d %b %Y')
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  def get_beginning_of_week(date)
    if date
      # the date format from JQuery date picker mm/dd/yyyy is not supported
      # so must be converted to standard yyyy-mm-dd.  this should be done
      # using jquery date format but it does not work somehow
      regex = /\d{2}\/\d{2}\/\d{4}/
      if date =~ regex
        date = DateTime.strptime(date,'%m/%d/%Y').strftime("%Y-%m-%d")
      end

      Date.parse(date).beginning_of_week
    else
      DateTime.now.beginning_of_week
    end
  end

  def get_hourly_count_by_date(data, date)
    a = Array.new

    data.each do |hc|
      if Date.parse(hc.calldate) == Date.parse(date)
        a << hc.clone
      end
    end

    return a
  end

end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h2>Mediation Counters</h2>
      <br />
      <%= form_tag(dashboard_index_path, method: "get") do %>
      <%= label_tag("Start date:") %>
      <%= text_field_tag :start_date %>
      <%= submit_tag "Search", :class => "btn btn-primary btn-sm" %>
      <% end %><br />

      <table class="table table-striped table-rounded table-bordered">
        <thead>
          <tr>
            <th>
              <center><%= link_to (fa_icon "backward"), :start_date => (@date.beginning_of_week-1) %></center>
            </th>
            <th colspan="6">
              <center>Week # <%= @current_week %></center>
            </th>
            <th>
              <center><%= link_to (fa_icon "forward"), :start_date => (@date.end_of_week+1) %></center>
            </th>
          </tr>
          <tr>
            <th></th>
            <th>Day</th>
            <th>Input</th>
            <th>Output</th>
            <th>Malformed</th>
            <th>Missing</th>
            <th>ZeroValue</th>
            <th>MinTooLow</th>
          </tr>
        </thead>
        <tbody>
          <% @daily_counters.each do |dc| %>
          <tr>
            <td>
              <center>
                <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#<%= dc.calldate %>-hourly">Hourly</button>
              </center>
              <div class="modal fade" id="<%= dc.calldate %>-hourly" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                      <h4 class="modal-title" id="myModalLabel"><%= display_date(dc.calldate) %></h4>
                    </div>
                    <div class="modal-body">
                      <table class="table table-striped table-rounded table-bordered">
                        <thead>
                          <tr>
                            <th>Hour</th>
                            <th>Input</th>
                            <th>Output</th>
                            <th>Malformed</th>
                            <th>Missing</th>
                            <th>ZeroValue</th>
                            <th>MinTooLow</th>
                          </tr>
                        </thead>
                        <tbody>
                          <% hourly_data = get_hourly_count_by_date(@hourly_counters, dc.calldate) %>
                          <% hourly_data.each do |hc| %>
                          <tr>
                            <td><%= hc.hour %></td>
                            <td><%= number_with_delimiter(hc.sum_records_in, :delimiter => ',') %></td>
                            <td><%= number_with_delimiter(hc.sum_records_out, :delimiter => ',') %></td>
                            <td><%= number_with_delimiter(hc.sum_malformed_data, :delimiter => ',') %></td>
                            <td><%= number_with_delimiter(hc.sum_missing_data, :delimiter => ',') %></td>
                            <td><%= number_with_delimiter(hc.sum_zero_value, :delimiter => ',') %></td>
                            <td><%= number_with_delimiter(hc.sum_min_too_low, :delimiter => ',') %></td>
                          </tr>
                          <% end %>
                        </tbody>
                      </table>
                    </div> <!-- / .modal-body -->
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div> <!-- /.modal-content -->
                </div> <!-- /.modal-dialog -->
              </div> <!-- /.modal fade -->
            </td>
            <td><%= display_date(dc.calldate) %></td>
            <td><%= number_with_delimiter(dc.sum_records_in, :delimiter => ',') %></td>
            <td><%= number_with_delimiter(dc.sum_records_out, :delimiter => ',') %></td>
            <td><%= number_with_delimiter(dc.sum_malformed_data, :delimiter => ',') %></td>
            <td><%= number_with_delimiter(dc.sum_missing_data, :delimiter => ',') %></td>
            <td><%= number_with_delimiter(dc.sum_zero_value, :delimiter => ',') %></td>
            <td><%= number_with_delimiter(dc.sum_min_too_low, :delimiter => ',') %></td>
            <!-- create the hourly modal -->
          </tr>
          <!-- /hourly modal -->
          <!-- TODO file level modal -->
          <% end %> <!-- daily_counters.each -->
        </tbody>
      </table>
    </div>
    <div class="col-md-1"></div>
  </div> <!-- /row -->
</div> <!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediationCounters</title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) if Rails.env.development? %>

</body>
</html>